# Required
version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - echo "Installing Packages:"
    - pip list
    - echo "Current Working Directory:"
    - pwd
    - echo "Directory Structure"
    - ls -R


python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true
